### ISSUE TITLE
Pull Request Processing Frequency

### ISSUE THREAD

**Issue by fhoesli** [hbunke/BibsOnGitHub#114]
Dear Hendrik Bunke
We hope you had a great summer time!?

In meantime we have left a recommendation for [BibsOnGithub](https://github.com/hbunke/BibsOnGitHub/blob/master/list.md).
So could you please consider our [pull request](https://github.com/hbunke/BibsOnGitHub/pulls) at the next possible opportunity?

Thanks a lot & greetings from Switzerland!
F. Hoesli on behalf of Lib4RI

**Comment by stweil** [comment]
Hello @fhoesli, the pull request processing frequency for this repository depends on many factors, and of course summer time is one of them. But you can be sure that all issues and pull requests will be handled, sooner or later (as in your case which I have merged now).

Kind regards to you and your team
Stefan Weil
