### ISSUE TITLE
Lizenz klären

### ISSUE THREAD

**Issue by stweil** [hbunke/BibsOnGitHub#17]
Wunsch: die Liste (und alle sonstigen Dateien dieses "Projektes") sollten unter einer freien Lizenz stehen (README.md entsprechend ergänzen) - auch wenn der bisherige Inhalt noch zu trivial dafür erscheint.

**Comment by hbunke** [comment]
Absolut einverstanden. Bin mir nur nicht sicher, was für eine Lizenz. Eine Code-Lizenz (GPL, BSD, ....),  eine Datenlizenz, eine andere CC-?

**Comment by stweil** [comment]
Ich schlage vor CC0 (https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by hbunke** [comment]
Weiß jemand, ob das mit GitHub Policies irgendwie in Konflikt stünde?

**Comment by stweil** [comment]
https://github.com/new bietet beim Anlegen eines neuen Repositories an, auch eine Lizenzdatei anzulegen. Die Auswahlliste enthält "Creative Commons Zero v1.0 Universal". Das Ergebnis sieht dann so aus wie in https://github.com/stweil/cc0-demo.

Siehe auch https://help.github.com/articles/open-source-licensing/.

=> kein Konflikt.

**Comment by stweil** [comment]
Die Lizenz steht inzwischen in README.md.
