### ISSUE TITLE
Make list international?

### ISSUE THREAD

**Issue by hbunke** [hbunke/BibsOnGitHub#42]
Should we open the list for international libraries? This tweet suggests to add the British Library: https://twitter.com/ndalyrose/status/819490433147531264

Any objections? Guess it would make sense, although there's already https://wiki.code4lib.org/Libraries_Sharing_Code

**Comment by stweil** [comment]
That site has a strong focus on libraries from the English speaking world.

IMHO a collection with a European focus would be nice, so why not open it for the British Library (they still are European, aren't they)?

**Comment by hbunke** [comment]
I like the european argument (esp. concerning Britain ;-). So let's do it. I guess we should introduce 'national' sections, at least for institutions? And language of README should be english.

**Comment by hbunke** [comment]
Oh, and we might need another name. The acronym 'BibsOnGithub' is strange anyways ;-)

**Comment by stweil** [comment]
`README.md` should be English, yes, but I'd keep the German text, maybe in a subdirectory as `lang/de/README.md` (can be extended for additional languages). People should not be sorted by nationality. Institutions should use their native name (not University Library for a German UB), optionally an English translation (is this really necessary?). If we add the country ISO code to each instititution (for example before or after the town), that would be sufficient for me. Adding country sections for institutions would also be fine, but is more difficult to parse by scripts.

**Comment by stweil** [comment]
> Oh, and we might need another name. The acronym 'BibsOnGithub' is strange anyways ;-)

Why? No, it's a very nice name, and I don't expect problems as "Bib" is Greek (so it fits to Europe). When I look at [Wikidata](https://www.wikidata.org/wiki/Q7075), I see more countries using the Greek form than the Latin one. You might add that explanation to the `README.md`, of course.

**Comment by osma** [comment]
Please add @NatLibFi

**Comment by stweil** [comment]
@osma, do you have a suggestion how the list should be organized? By country? Or flat (with a country indicator)?

**Comment by osma** [comment]
Well I don't have an exact use case in mind, you probably know the requirements better. By country would make sense to me, but do as you like.

**Comment by hbunke** [comment]
I've added @NatLibFi, @britishlibrary, and @BL-Labs. List is now open for libraries and library developers from any country (mainly from Europe, I guess). README.md is quick'n'dirty translated, please improve or complete.

I've not added any additional sections for international entries. After all, we are all Europeans, aren't we ;-)  Guess this should work for now (keep it simple), later on we might think about an improved data structure.

I'll close this issue. For further discussions please open a new one.

**Comment by stweil** [comment]
Can we close this issue?
