### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by hbunke** [hbunke/BibsOnGitHub#43]
While the term `BibsOnGitHub` might be understood by germans, it is neither correct english nor very meaningful for non german speakers. In case of opening the list for european libraries and developers we should rename the repo.

Suggestions for a new title, anyone?

**Comment by krugar** [comment]
given #42, EuropeanLibrariesOnGithub seems to be the obvious choice?

**Comment by stweil** [comment]
I disagree. See my comment on PR #42.

**Comment by hbunke** [comment]
Good point, @stweil ! I'll leave the issue open so others can make suggestions. We can decide that later, I guess.

**Comment by stweil** [comment]
Just a side remark: our students (also the foreign ones) like the name "bib".

**Comment by krugar** [comment]
@stweil has a valid point, and another benefit of "bib..." over "libr..." is the disambiguation from "software libraries", which might be the most prevalent context assumption on github. i'm somewhat confuzzled by the mixing of languages, tho.

"BibliosFromEurope"? Do we need the "...OnGithub" in the name, or could that move to the readme? Do we need "FromEurope"? I mean, if we're already joking (in the best of spirits) about the British Library still being in the EU, then how do the Swissbib folks feel? 😉  They surely belong on the list, right? Maybe something along the lines "OpenSourceBiblios" or "BibliosWithOpenSource" opens up a fitting scope?

Names are hard

**Comment by hbunke** [comment]
> Names are hard
So true! 

When I opened the repo I didn't think too much about the name, it was just a spontaneous idea. But sometimes those still might be the best ones ;-)

**Comment by stweil** [comment]
It looks as if there is no longer a desire to change the well established repository name. Therefore I'll close this issue.
