### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by nichtich** [hbunke/BibsOnGitHub#6]
Ein Privacy-Hinweis wäre angebracht. An der VZG haben mehrere Mitarbeiter GitHub-Accounts die ansonsten nicht auf GitHub tätig sind. Prinzipiell lassen sich die meisten GitHub-Accounts Personen zuordnen, wenn die Zuordnung aber nicht wirklich offensichtlich ist, sollte niemand "geoutet" werden.

**Comment by hbunke** [comment]
Wir könnten uns auf die Regel einigen, dass Profile von Einzelpersonen nur aufgenommen werden, wo die Zuordnung zu einer bibliothekarischen Organisation im Profil selbst ersichtlich ist (die Zuordnung also auch explizit gewollt ist). Ich würde außerdem einen Hinweis reinschreiben, dass wer dennoch nicht in der Liste auftauchen will, eine kurze Nachricht an mich (oder dich ;-) schreiben sollte, dann kommt der Eintrag raus.

**Comment by stweil** [comment]
@nichtich, hast Du einen Vorschlag, wie der Hinweis aussehen sollte? Oder ist das bisherige Vorgehen ausreichend, dass wir bei Pull Requests auf die Rückmeldung der Betroffenen warten (wobei der PR ja auch schon Info "outet")?

**Comment by stweil** [comment]
@nichtich, can this issue be closed?
